name: todoapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  get: ^4.6.6
  intl: ^0.19.0
  permission_handler: ^11.3.0
  sqflite: ^2.4.1
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  flutter_timezone: ^4.1.1
  rxdart: ^0.28.0
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
